### ISSUE TITLE
Option-# Changes Session, But Also Insert Character

### ISSUE THREAD

**Issue by chriscoyier** [elanthia-online/illthorn#105]
<img width="212" alt="Screen Shot 2020-08-08 at 5 53 07 AM" src="https://user-images.githubusercontent.com/69156/89710887-9982b780-d93b-11ea-93ad-7e62a4241f46.png">

Option 1 inserts ¡
Option 2 insert ™

(macOS, US keyboard)

**Comment by chriscoyier** [comment]
Related to this, if you have something typed into the CLI prompt, then switch sessions, it's still there (only unlikely to be what you want, as it's a different character).

**Comment by ondreian** [comment]
> if you have something typed into the CLI prompt, then switch sessions, it's still there (only unlikely to be what you want, as it's a different character).

I actually use this as a feature, not a bug.  For instance when I want to do `ask rhet for bounty` (as an example) but it isn't in the autocomplete history of 1 character, I can `alt + <n>` and then autocomplete and `alt + <n>` back.  Or when i am running a lich `;e` script across multiple characters for instance.

**Comment by chriscoyier** [comment]
All good then! 👍
