### ISSUE TITLE
Weird Rooms / Killing Feed

### ISSUE THREAD

**Issue by chriscoyier** [elanthia-online/illthorn#107]
The furrier on Teras seems to just kill the client for me. It gets in this weird state where I can't do anything. 

<img width="408" alt="Screen Shot 2020-08-10 at 12 27 01 PM" src="https://user-images.githubusercontent.com/69156/89838786-f9868300-db20-11ea-9c18-9ee9400a4190.png">

I have to disconnect and re-connect again. No JS errors in the console.

**Comment by ondreian** [comment]
Yeah, I'm hoping the parser rewrite fixes these really strange edge cases, using `DOMParser` should be significantly more error resilient.  I have also received reports from a couple friends that when you "level up" it crashes the feed as well, which is annoying to say the least
