### ISSUE TITLE
Whitespace in Feed

### ISSUE THREAD

**Issue by chriscoyier** [elanthia-online/illthorn#113]
<img width="748" alt="Screen Shot 2020-08-19 at 12 46 58 PM" src="https://user-images.githubusercontent.com/69156/90696563-58d74800-e231-11ea-87b6-7219dffb769c.png">

Inspecting that particular one, I see a `<span>` with fairly normal content inside it. But we do set everything in inside the feed to `white-space: pre-wrap` in CSS, so if it happened to start with a line-break, it will render as a line break. Maybe we can safely `.trim()` the white space from all feed elements before appending?

**Comment by ondreian** [comment]
When there is a leading `<a>` element in a `<span>` there can still be leading whitespace
