### ISSUE TITLE
The Keyboard Command for Switching Sessions Also Inserts Characters

### ISSUE THREAD

**Issue by chriscoyier** [elanthia-online/illthorn#132]
on macOS anyway...

<img width="264" alt="Screen Shot 2020-09-04 at 10 54 15 AM" src="https://user-images.githubusercontent.com/69156/92271647-076bc180-ee9d-11ea-8c5d-4ef94bcaefc3.png">

**Comment by ondreian** [comment]
Is this still the case? I don't have a mac to test.

**Comment by chriscoyier** [comment]
I'll try to test today

**Comment by chriscoyier** [comment]
fixed
