### ISSUE TITLE
Webpack Issue

### ISSUE THREAD

**Issue by BryanSchuetz** [elanthia-online/illthorn#134]
Really hate to say this...I'm getting this error when running the most recent Master:

<img width="1254" alt="Screen Shot 2020-09-10 at 7 04 18 AM" src="https://user-images.githubusercontent.com/174269/92722005-ef7cbd80-f334-11ea-965d-db3df4c22102.png">

**Comment by BryanSchuetz** [comment]
err...duhh. Forgot to do that. Looks like it's working. Thanks.

**Comment by ondreian** [comment]
Don't worry, a variant of this happened to me on Tuesday at work also.  https://twitter.com/benjaminclos/status/1303359541179027458
