### ISSUE TITLE
Built App still looking for some assets via Webpack.

### ISSUE THREAD

**Issue by BryanSchuetz** [elanthia-online/illthorn#135]
Was making an executable to enjoy the new icon...and noticed that the built app is still looking for some assets via Webpack, which I'm assuming it shouldn't be. The app was built using `yarn make` 

<img width="1278" alt="Screen Shot 2020-09-10 at 4 35 13 PM" src="https://user-images.githubusercontent.com/174269/92802153-41006900-f384-11ea-91ac-b1a1f0eff949.png">

**Comment by ondreian** [comment]
I think I fixed this by adding the PRELOAD entry, let me know if you are still seeing it on your platform.
