### ISSUE TITLE
Auto-connection logic doesn't appear to work

### ISSUE THREAD

**Issue by jasedit** [elanthia-online/illthorn#147]
Documentation states that one can simply run `:connect` and Illthorn will attempt to detect lich instances with open ports and attach, which doesn't seem to work as expected. Or perhaps it is meant to simply autoscan without the command, and isn't detecting the instance on my machine? I run the command `ruby gtk3.rbw --without-frontend --detachable-client=8000 --login Character` and then launch Illthorn, but no auto-connection happens.

**Comment by ondreian** [comment]
That will not match the pattern of looking for a `lich.rb` file

**Comment by ondreian** [comment]
https://github.com/elanthia-online/illthorn/blob/master/src/autodetect/index.js#L10-L12
explains how it matches from the `ps` list
