### ISSUE TITLE
mark.speech & mark.whisper parsing

### ISSUE THREAD

**Issue by BryanSchuetz** [elanthia-online/illthorn#165]
I've noticed that the new parser captures a prompt within the speech and whisper elements. I've been setting those text elements apart from the rest of the stream in my theme—which now looks odd with the prompt in there. Any way to remove them?

<img width="323" alt="Screen Shot 2020-11-30 at 8 49 12 PM" src="https://user-images.githubusercontent.com/174269/100687666-b27e0100-334e-11eb-869e-a1bdc30cab44.png">

**Comment by BryanSchuetz** [comment]
I mean, I suppose I could just hide them.

**Comment by ondreian** [comment]
Nah, I will fix this, it needs to work a bit better for the stream window
anyway

**Comment by ondreian** [comment]
related to #163
