### ISSUE TITLE
Out-of-order Vitals

### ISSUE THREAD

**Issue by chriscoyier** [elanthia-online/illthorn#169]
Once in a while they load in in a weird order. Can we enforce an order? 

See how stance is listed first here:

<img width="338" alt="Screen Shot 2020-12-04 at 6 52 50 AM" src="https://user-images.githubusercontent.com/69156/101196997-5f3dd400-3616-11eb-8a27-676b0cb4e848.png">

**Comment by ondreian** [comment]
Yeah, definitely should have an order, should we implement this using the css `order` property so that skins can adjust it, if they like?
