### ISSUE TITLE
Autodetect fails :  macOS and Win10

### ISSUE THREAD

**Issue by OSXLich-Doug** [elanthia-online/illthorn#180]
Detect for active ruby sessions fails on 

macOS 10.15.7
macOS 11.1
Win 10 Pro

Ruby 2.6.6 with standard GTK3 gems

**Comment by ondreian** [comment]
What command are you launching with

**Comment by OSXLich-Doug** [comment]
It was actually the name of the lich file on the mac.

ruby ~/Desktop/betalich/gtk3.rbw --login Name --detachable-client=port --without-frontend

That failed.  But while chatting with Ineum, I changed the name of the lich file back to lich.rbw and tested, and that worked.

The Windows autdetect still fails in that scenario.  And, I will be testing paths with imbedded spaces, just because that seems to be a non-Unix thing these days.
