### ISSUE TITLE
Feature Request - CLI method to connect with Illthorn

### ISSUE THREAD

**Issue by OSXLich-Doug** [elanthia-online/illthorn#185]
Working with Cabal and Ruby 3.0 because Lich requires massive updates to work with 3.0

Have recreated login abilities most users are familiar with to help speed / incent transition.

Need a way to open Illthorn with args so I can pass it commands to automatically connect to the Game.thread

**Comment by ondreian** [comment]
Good idea, adding a CLI like `google-chrome` has for opening URLs, but to launch sessions would be nice.  If the launcher already uses a pattern that's autodetectable might be relatively trivial

**Comment by ondreian** [comment]
This should be done with the session descriptor .json files I added to Lich awhile ago, it's much more robust (and cross-platform)
