### ISSUE TITLE
Dropped Room Name/Desc

### ISSUE THREAD

**Issue by BryanSchuetz** [elanthia-online/illthorn#189]
I've noticed that occasionally I'll walk into a room and the `roomName` and `roomDesc` never populate. I see it often around the well in WL—but have seen it here and there elsewhere.

<img width="1217" alt="Screen Shot 2021-02-11 at 5 53 29 AM" src="https://user-images.githubusercontent.com/174269/107628590-df903f00-6c2e-11eb-95de-f8d7fb213d35.png">

**Comment by ondreian** [comment]
hmm interesting, wonder if there is something special about those rooms
specifically.  Thanks!

**Comment by BryanSchuetz** [comment]
Maybe it's something to do with my setup—though I think I'm pretty sure I'm on the latest version. I've also been seeing missed updates to the prompt status (coming in and out of hiding, stun, etc.) and with hand status (prepared spells, what's in a hand, etc.).

**Comment by chriscoyier** [comment]
weird! I go to the town well all the time and don't see that. Doesn't seem to be theme-related there as the DOM is just totally missing the room stuff. 

The status stuff is missing for me too, though. I agree that was pretty cool. It would be fun to icon-ize the status-es like having special icons for hidden/stunned/prone, etc.

**Comment by BryanSchuetz** [comment]
FWIW, on the off chance that my antiquated version of lich was causing problems I upgraded to the GTK3 version...and still see issues. Can see here...
<img width="1215" alt="Screen Shot 2021-02-11 at 5 06 10 PM" src="https://user-images.githubusercontent.com/174269/107704817-db463f00-6c8b-11eb-9f57-c8fdbc503004.png">
