### ISSUE TITLE
Dark-King Theme's MonsterBold color should be orange, not red.

### ISSUE THREAD

**Issue by deatrys** [elanthia-online/illthorn#195]
Dark-King Theme's MonsterBold color should be orange, not red.

**Comment by chriscoyier** [comment]
Does it seem like a bug? Red kinda feels more monster-y to me I guess, but I also don't care that much. 

This file controls all that https://github.com/elanthia-online/illthorn/blob/master/src/app/styles/themes/dark-king.scss

**Comment by vaneseltine** [comment]
Presumably not a bug; it's a theme color choice. I've been using red as monster bold for a couple decades, though yellow is more popular.

**Comment by deatrys** [comment]
Oh, I thought there was sort of a standard.
Well, long-term, being able to customize them beyond the theme default, could be nice.  Meaning without having to go into the css.
