### ISSUE TITLE
Roundtime indicators

### ISSUE THREAD

**Issue by ondreian** [elanthia-online/illthorn#20]
We should have some sort of RT indicator, maybe a circle svg/gauge in the right-hand side of the CLI bar?

Absolutely open to suggestions here.

**Comment by chriscoyier** [comment]
The question is... do people like seeing the NUMBER left? Or just a bar good enough? 

If it's just a bar maybe something chill right next to the command bar itself (the point being that roundtime is what prevents new commands, so they are highly related). 

![roundtime](https://user-images.githubusercontent.com/69156/86483699-72681300-bd09-11ea-94ee-990f1fc8bea8.png)

**Comment by ondreian** [comment]
I'm a fan of minimal, i'm not sure there is a lot of usefulness in having a specific number, most people will be using scripts that manage handling spamming commands where they need to be as close to roundtime completion as possible anyway.

Some commands can generate extraordinary amounts of RT (> 5m) so we might need to be careful if we use a percentage-based view of that.
