### ISSUE TITLE
minimizable session menu

### ISSUE THREAD

**Issue by ondreian** [elanthia-online/illthorn#21]
currently the session menu displays both the character name and their `Alt + <n>` shortcut, but we could have it minimized unless you "sticky" hold the `alt` key for 500ms or something to increase screen real estate

**Comment by chriscoyier** [comment]
Maybe it stays minimized for the most part, shows the first name of the character and the number, and you can hover it for more details if you need?

<img width="467" alt="Screen Shot 2020-07-03 at 1 17 36 PM" src="https://user-images.githubusercontent.com/69156/86495772-93435f00-bd2f-11ea-8455-cf5951d9124d.png">

**Comment by ondreian** [comment]
Super cool, this is exactly what I was thinking
