### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by chriscoyier** [elanthia-online/illthorn#27]
I would find it beneficial to have a Prettier config in here so we're all auto-formatting code in the same style.

**Comment by ondreian** [comment]
That's fine by me, I have no strong feelings on code formatting beyond [comma-first notation](https://gist.github.com/isaacs/357981) since we are not using Typescript, if you have some sane defaults feel free to open a PR.

**Comment by chriscoyier** [comment]
Done did it.
