### ISSUE TITLE
Deaths Panel

### ISSUE THREAD

**Issue by chriscoyier** [elanthia-online/illthorn#34]
Avalon & Stormfront offer this widget. I think it's kinda nice as it reduces noise in the main game window.

**Comment by chriscoyier** [comment]
This is sort of like a "Stream" and with chat/thoughts we opted not to put Stream-like content in sidebar panels, so probably a bit more strategizing is in order here.

**Comment by ondreian** [comment]
deaths are technically a stream, I probably just forgot to add them to the `:stream` command
