### ISSUE TITLE
Window Draggability

### ISSUE THREAD

**Issue by chriscoyier** [elanthia-online/illthorn#35]
It's hard to find a spot to grab the window to drag it around. For me I have to find a spot in between the buttons to do it at all.

<img width="268" alt="Screen Shot 2020-07-03 at 12 22 31 PM" src="https://user-images.githubusercontent.com/69156/86493852-faf5ac00-bd27-11ea-8b16-a3064d4abf87.png">

**Comment by chriscoyier** [comment]
Quirk: if the window ISN'T active, it's easier to click in that area and grab it, but once it's active it's harder.

**Comment by BryanSchuetz** [comment]
I noticed this as well. There's a webkit property for making frameless windows draggable, I just added it to `#app` in my user.css and it makes the window super draggable:

`#app{-webkit-app-region: drag;}`

I could add it into app.css if we think this solves the problem reasonably.

**Comment by chriscoyier** [comment]
It doesn't seem to do anything for me. Weird? 

Maybe we could do a thin bar along the top? Or maybe not make the window frameless at all?

**Comment by BryanSchuetz** [comment]
That is weird, can see it working here: https://share.getcloudapp.com/lluJAbly 

If we do keep it like this, I suppose we'll have to specify `no-drag` for the list items in `#sessions`—I'm assuming the idea is that you can click on the session blocks to switch the current session? 

Also, not against just including a title bar either I suppose.

**Comment by chriscoyier** [comment]
Ah yes, working for me now, not sure what was happening before. 

I think...

```
#sessions {
  -webkit-app-region: drag;
}
#sessions ol li {
   -webkit-app-region: no-drag;
}
```

is a nice way to handle this.

**Comment by ondreian** [comment]
this seems closable
