### ISSUE TITLE
Window size on launch

### ISSUE THREAD

**Issue by BryanSchuetz** [elanthia-online/illthorn#58]
Currently, we set `mainWindow.maximize()` after creating the main window—to fill up all the space on the screen. I generally play on a large 5k monitor and find this kind of annoying. Can we set a more reasonable size, when launching the window?   `1500X1000` perhaps. Happy to make a PR with this change in it.

**Comment by ondreian** [comment]
Seems like this should probably be handled by `Settings` so that we store the window size that a user has specifically set (for tiling, etc) and just restore it on application close

**Comment by BryanSchuetz** [comment]
Makes sense. I should be able to do that.
