### ISSUE TITLE
refactor vimish commands

### ISSUE THREAD

**Issue by ondreian** [elanthia-online/illthorn#59]
currently they are all in the same file which was nice for the initial prototype, but they should all be broken out into separate files to no longer violate SRP and make the chance of git conflicts significantly lower

https://github.com/elanthia-online/illthorn/blob/master/src/vimish/index.js

Something like:
```
vimish/
   commands/
       meta.js
       ui.js
       ...etc
```

**Comment by chriscoyier** [comment]
For sure. 

I can take this if nobody else really wants it.

**Comment by ondreian** [comment]
@chriscoyier currently we're using just `exports[key]` as the dictionary.  I think this might make sense though to use a real registry and `new Map()` which parses out the root vimish command, versus the arguments.  Potentially we can add support for variadic arguments then.  Thoughts?

**Comment by ondreian** [comment]
I'll break out the other features to specific issues
