### ISSUE TITLE
figure out how to use electron-compile for hmr

### ISSUE THREAD

**Issue by ondreian** [elanthia-online/illthorn#60]
[`electron-compile`](https://github.com/electron-userland/electron-compile) says it has a bunch of features like hmr for sass, etc.

Would be nice to add a better dev workflow around that

**Comment by chriscoyier** [comment]
This (or something like it) would be nice. Reloading to see changes isn't terrible, but a lot of times you have to wait around for something (a stream chat message, a death, etc) to make sure things are working and not having to do that would be much nicer dev experience. (I guess saved logs would help there too.)

**Comment by BryanSchuetz** [comment]
It looks like electron-complie is no longer maintained. I did notice that we're already including the webpack plugin for electron-forge...so I'd think you could setup webpack to recompile the SASS for us....

**Comment by ondreian** [comment]
I'd also like to insulate us from the seemingly arbitrary JS syntax changes that happen with electron upgrades.  I spent a weekend navigating that mess, and as much as I hate babel, it might be the only path forward short of typescript.

Though typescript is my personal preference, I am hesitant to do it for this project because I want people to feel like they can contribute easily.

**Comment by chriscoyier** [comment]
There has just _gotta_ be a way to get that webpack plugin to do the job for us. Would be nice to just `yarn start` and go. I tried it a while back but got stuck here:

https://www.electronforge.io/config/plugins/webpack

This implies that we "must" provide two webpack config files, but we don't have either, and I wasn't sure where to put them or how to wire them up. Seems like that might be the ticket though, as then that's the config for setting up Sass.

> Though typescript is my personal preference, I am hesitant to do it for this project because I want people to feel like they can contribute easily.

I'd vote against TypeScript for the same reasons. If we end up getting pulled in that direction, that's fine, but it's out of my wheelhouse and I'd be trying to learn it for the first time myself.

**Comment by chriscoyier** [comment]
Closing... HMR is in place. It doesn't always work, but such is the nature of HMR, not all files can be hot-swapped. Works pretty well for CSS and at least gives it a shot for JS. 

<img width="393" alt="Screen Shot 2020-09-26 at 1 40 58 PM" src="https://user-images.githubusercontent.com/69156/94349918-10fccb00-fffe-11ea-8793-b4587e33e420.png">
