### ISSUE TITLE
back injuries

### ISSUE THREAD

**Issue by chriscoyier** [elanthia-online/illthorn#66]
I think it might be ignoring them.

<img width="810" alt="Screen Shot 2020-07-11 at 7 10 44 PM" src="https://user-images.githubusercontent.com/69156/87237363-4e13d280-c3aa-11ea-9b9a-66b2abc20995.png">

**Comment by ondreian** [comment]
I'm not sure what's going on here, I haven't been able to get a back injury recently to inspect the feed, I'll get a f2p and ambush him today if I keep being unlucky.
