### ISSUE TITLE
Include spell name in title attribute for list items under active spells

### ISSUE THREAD

**Issue by BryanSchuetz** [elanthia-online/illthorn#69]
I've been truncating the spell name in the active-spells panel because I don't like the way it looks when it wraps. It would be nice if we also included the spell name in a title attribute for the list item so you could hover over the truncated name and see the full name. 

<img width="403" alt="Screen Shot 2020-07-13 at 10 32 55 AM" src="https://user-images.githubusercontent.com/174269/87317770-74925480-c4f5-11ea-8fa3-d3573e04fc87.png">

This would hep to distinguish between multiple ranks of the same spell (e.g. Elemental Defense I, II, III). If we think this makes sense, I'm happy to make the change in `active-spells`

**Comment by chriscoyier** [comment]
One thing to consider with the `title` attribute is that it has that hover/popup thing that you cannot control in any way.

An alternative might be to add a `data-spell-name` attribute and then use that to construct a hover effect if desired. 

Stretch goal... add things like `data-spell-description` or `data-spell-effects="+5 TD"` for more optional scalability. That introduces some extra technical debt though as I assume those kinds of things change over time.

**Comment by ondreian** [comment]
Data attributes are not very accessible, really what I think is necessary
here is probably a lookup table to show both spell number and spell name

**Comment by BryanSchuetz** [comment]
Is that kind of data available from the stream? I'm thinking number and spell-name might be...but not the kind of thing Chris is talking about. I'm assuming there's no JSON endpoint on the game server we can hit for a spells table—would we be OK scraping the wiki? That's not maintained officially is it?

**Comment by chriscoyier** [comment]
> Data attributes are not very accessible

They aren't, but `title` isn't either (it's not read by Assistive Tech). If we were actually truncating the text, we'd need some kind of solution, but the text isn't actually truncated, it's all in the DOM properly. 

For other spell information (the lookup table sounds very smart), we could chuck that stuff in the DOM too and hide/show it based on settings potentially.

**Comment by ondreian** [comment]
Maybe something like:
```
401 / Elemental Defense...
406 / Elemental Defense...
```
Or however we decide to join them, but would at least give you all the info you need in the same row, and still allow truncating


> Is that kind of data available from the stream?
Not really, it's either spell numbers or spell names, you can set it with with the `FLAG` verb

> I'm thinking number and spell-name might be...but not the kind of thing Chris is talking about. 
Nah, I was just trying to think of a way to handle truncation but still display all necessary info.

> I'm assuming there's no JSON endpoint on the game server we can hit for a spells table—would we be OK scraping the wiki? 
We'll be fine scrapping the wiki for most things, I've done it [for other stuff](https://github.com/ondreian/Olib/blob/master/scripts/fetch-creatures)

If there are data issues, you can just ping me and I'll edit whatever is wrong, I should still have authorship privileges there.

**Comment by ondreian** [comment]
This is mostly done, maybe needs a couple followups if there is missing data.
