### ISSUE TITLE
remove customCSS system in favor of themes

### ISSUE THREAD

**Issue by ondreian** [elanthia-online/illthorn#80]
having the CustomCSS `user.css` file is redundant, we should instead use the unified theme system.

Offering a `:theme fork` command or something similar to base a theme off one of the existing ones.

**Comment by chriscoyier** [comment]
I'm cool with this. I really can't see user.css being used that much.

Although what I imagine is that ultimately this thing turns into a single application file that sits on someone's machine, and they don't really have access to the internal files that is that right? Like Slack is an Electron app and I can't crack open Slack and edit the CSS in there. So the interesting part about a user.css file is that it lives outside the app somewhere on their system, giving them the ability to hack on stuff from the outside. 

I imagine a really low number of people would ever do that though? I dunno. More likely is that I'm misunderstanding what people have access to with a built app. If they `:theme fork original` or something, do those new files go somewhere a user would have access too without having to run the dev environment?

**Comment by ondreian** [comment]
Anything that is modifiable will need to live in `appData`, like `user.css` does now
