### ISSUE TITLE
left panels shouldn't be so jumpy

### ISSUE THREAD

**Issue by ondreian** [elanthia-online/illthorn#89]
Currently, because all of the panels dynamically resize, the compass can jump around, etc.  Ideally:
```
<vitals fixed-height>
<active-spells dynamic-height+scrollbar>
<compass fixed-height>
```
so that the vitals & compass never change where they are oriented along the Y-axis

**Comment by BryanSchuetz** [comment]
This might be improved by addressing the empty/loading/loaded states of the panels (I think Chris was working on that). The Stance list item, for instance, won't show up until you change it..at which point the size of the vitals panel shifts. Or reordering them ?—injuries and spells are really the only ones that would need to adjust size...

It would be cool if you could drag them to re-arrange...but maybe that's a V2 kind of thing.

**Comment by ondreian** [comment]
I'm not sure about draggable panels, it sounds cool, but I personally prefer to have a "sane path forward", drag and drop especially with dynamically sized content adds a combinatorial explosion problem which makes:

1. testing harder
2. skinning harder

I'm not sure the tradeoff is worth it.

**Comment by BryanSchuetz** [comment]
Fair enough. I like your framing of it as a VS Code for Gemstone.
