### ISSUE TITLE
:explain meta command

### ISSUE THREAD

**Issue by ondreian** [elanthia-online/illthorn#9]
we should have an `:explain` metacommand that has the ability to show help menus/explanations.

`:explain ui` would generate some help docs about the `:ui` command as an example.  Maybe using Markdown?

**Comment by chriscoyier** [comment]
Do you envision that it shoots some documentation into the main feed?

Or pops open a modal or other bit of UI with the documentation? 

I'd think I'd lean toward the latter, and then maybe not even require that you know this command to open it, could be a button that says "Command Reference" or the like that opens it.

**Comment by ondreian** [comment]
That would be cool. I also think maybe we need some `alt` text or hover explain on how to interact with components with the vimish commands.

Like if you hover on a ui component it has some tooltip saying `:ui vitals off` to whatever, and then a way to set the tooltips to off is ideal.

**Comment by chriscoyier** [comment]
modal-y way: https://github.com/elanthia-online/illthorn/pull/49

**Comment by ondreian** [comment]
The legwork for this is there now, thanks.
