### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by BryanSchuetz** [elanthia-online/illthorn#93]
Was playing around with adding an avatar to the session box, e.g.:

<img width="604" alt="Screen Shot 2020-07-29 at 11 09 47 AM" src="https://user-images.githubusercontent.com/174269/88817998-34d19b00-d18c-11ea-96b9-305e216dd3ac.png">

And was thinking it would be cool if we allowed the user to set an avatar for each session—they could be roughly equivalent to character classes, e.g.:

<img width="1030" alt="Screen Shot 2020-07-29 at 11 07 53 AM" src="https://user-images.githubusercontent.com/174269/88818196-6fd3ce80-d18c-11ea-9a6b-2b11da7a1cd8.png">

Could maybe piggyback off the session naming methods..or could maybe even pickup on class from Lich? Not sure if that kind of value thing might be saved in game entry data? 

Or, just set a generic one as default and let people set something like `:avatar ranger2`

Anyway, just a thought.

**Comment by chriscoyier** [comment]
I kinda love these. I would think people get the concept of generic avatars. It's a fun way to tell accounts apart. Where did they come from? Maybe the original artist would be down for some basic alterations? For example, they all kinda look like white people and seems like it would be fairly easy to make skin tone variations of them.

**Comment by BryanSchuetz** [comment]
Grabbed from an icon aggregator I have access to through work. All SVG so should be easy enough to make skin tone variations ourselves. I _think_ I can reach out to artist for extras—was thinking none of them really fit for empath or bard for instance.
