### ISSUE TITLE
Icon Path/macOS icon

### ISSUE THREAD

**Issue by BryanSchuetz** [elanthia-online/illthorn#97]
Am I the only one who sees this error every time I try to `yarn start`? 

<img width="488" alt="Screen Shot 2020-07-30 at 11 03 56 AM" src="https://user-images.githubusercontent.com/174269/88941253-cad1f800-d256-11ea-81bc-ca0434c68e6e.png">

Seems like it's looking for the icon in the wrong place: `titleBarStyle: "hidden",
    icon: "/src/app/png/64x64.png",` when it should be looking in `./build/icons/`. I think this deceleration is just a windows thing...the icon is for the "task-bar"? For MacOS I think we'd need an .icns file, and would have to set it as a flag when packaging.

**Comment by BryanSchuetz** [comment]
I changed the path to the icon here #98 

I can add the bits for the MacOS icon if that's the icon we want to go with.

**Comment by ondreian** [comment]
Hmm, I don't see this on Linux, I'll pull this and see how the `.deb` file from `electron-forge` is after
